# Generated by Django 4.1 on 2024-01-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gitlink',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='livelink',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
