# Generated by Django 4.1 on 2024-01-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project_gitlink_project_livelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gitlink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='livelink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
